/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"
#include "MailNewsTypes2.idl"

interface nsIMsgIncomingServer;

/**
 * JMAP folder interface.
 */
[scriptable, uuid(11112222-3333-4444-5555-666677778888)]
interface IJmapFolder : nsISupports
{
  readonly attribute AUTF8String folderId;
};
