/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

#include "nsISupports.idl"

/**
 * JMAP-specific incoming server interface.
 */
[scriptable, uuid(12345678-90ab-cdef-1234-567890abcdef)]
interface IJmapIncomingServer : nsISupports
{
  /** The URL for the JMAP server. */
  attribute ACString jmapUrl;

  /** The JMAP account ID. */
  attribute ACString jmapAccountId;
};
